loading_dir: results/ba_chienn_rwse

config_files:
  - configs/add_test_set.yaml
  - configs/add_rwse.yaml
  - configs/datasets/binding_affinity.yaml
  - configs/models/chienn.yaml
  - configs/general.yaml

n_best: 3