loading_dir: results/ba_ptree/edge/split/reduction_rwse

config_files:
  - configs/add_test_set.yaml
  - configs/add_rwse.yaml
  - configs/chem/separate_tree.yaml
  - configs/chem/remove_duplicate_edges.yaml
  - configs/datasets/binding_affinity.yaml
  - configs/models/ptree_default.yaml
  - configs/general.yaml

n_best: 3
