loading_dir: results/ba_ptree/vertex/cyclic

config_files:
  - configs/add_test_set.yaml
  - configs/add_rwse.yaml
  - configs/chem/cyclic_trees.yaml
  - configs/vertex_mode.yaml
  - configs/datasets/binding_affinity.yaml
  - configs/models/ptree_circle.yaml
  - configs/general.yaml

n_best: 3
