loading_dir: results/ba_ptree/vertex/selective_rwse_e

config_files:
  - configs/add_test_set.yaml
  - configs/add_rwse.yaml
  - configs/chem/tetra_selective.yaml
  - configs/vertex_mode.yaml
  - configs/datasets/binding_affinity.yaml
  - configs/models/ptree_e.yaml
  - configs/general.yaml

n_best: 3
