loading_dir: results/tox21_ptree/edge/cistrans

config_files:
  - configs/add_test_set.yaml
  - configs/chem/cis_trans.yaml
  - configs/datasets/tox21.yaml
  - configs/models/ptree_default.yaml
  - configs/general.yaml

n_best: 3