loading_dir: results/tox21_ptree/edge/split/reduction

config_files:
  - configs/add_test_set.yaml
  - configs/chem/remove_duplicate_edges.yaml
  - configs/chem/separate_tree.yaml
  - configs/datasets/tox21.yaml
  - configs/models/ptree_default.yaml
  - configs/general.yaml

n_best: 3
