loading_dir: results/ez_chienn

config_files:
  - configs/add_test_set.yaml
  - configs/hyper_param_opt/epoch_reduction.yaml
  - configs/datasets/ez_dataset.yaml
  - configs/models/chienn.yaml
  - configs/general.yaml

n_best: 2