loading_dir: results/bace_ptree/edge/cyclic_reduced_light

config_files:
  - configs/add_test_set.yaml
  - configs/chem/cyclic_trees_light.yaml
  - configs/chem/remove_duplicate_edges.yaml
  - configs/add_rwse.yaml
  - configs/datasets/bace.yaml
  - configs/models/ptree_default.yaml
  - configs/general.yaml

n_best: 3