loading_dir: results/tox21_ptree/edge/cyclic_reduced_minimal

config_files:
  - configs/add_test_set.yaml
  - configs/chem/cyclic_trees_minimal.yaml
  - configs/chem/remove_duplicate_edges.yaml
  - configs/datasets/tox21.yaml
  - configs/models/ptree_circle.yaml
  - configs/general.yaml

n_best: 3
