output_dir: results/rs_chienn
config_files:
  - configs/datasets/rs_dataset.yaml
  - configs/models/chienn.yaml
  - configs/general.yaml
  - configs/hyper_param_opt/subsetting.yaml
num_samples: 2 # currently reduced for development