model:
  mode: custom
  hidden_dim: 128
  modules:
    0:
      type: graph_embedding
      parameter:
        node_type: linear
        edge_type: linear
    1:
      type: linear_dummy
      times: 5
  head:
    type: san_head
    n_layer: 3
    pool_function: add
