loading_dir: results/br_ptree/edge/default

config_files:
  - configs/add_test_set.yaml
  - configs/datasets/binding_rank.yaml
  - configs/models/ptree_default.yaml
  - configs/general.yaml

n_best: 3