loading_dir: results/bace_ptree/vertex/cistrans_advanced_rwse

config_files:
  - configs/add_test_set.yaml
  - configs/use_separate_inv.yaml
  - configs/chem/cis_trans.yaml
  - configs/add_rwse.yaml
  - configs/vertex_mode.yaml
  - configs/datasets/bace.yaml
  - configs/models/ptree_inv.yaml
  - configs/general.yaml

n_best: 3