output_dir: results/ez_chienn_unmasked

config_files:
  - configs/unmasked.yaml
  - configs/hyper_param_opt/epoch_reduction.yaml
  - configs/datasets/ez_dataset.yaml
  - configs/models/chienn.yaml
  - configs/general.yaml

search_space:
  model:
    hidden_dimension: tune.choice([128, 256])
    modules:
      1:
        times: tune.choice([5, 10])
        parameter:
          dropout: tune.choice([0.0, 0.2])
  optimizer:
    base_learning_rate: tune.choice([0.001, 0.0001])

hyper_settings:
  scheduler:
    grace_period: 2
    reduction_factor: 3
    brackets: 1
  max_concurrent_trials: 2
  num_samples: 10 # set to this as this optimization is quite simplistic