loading_dir: results/rs_ptree/vertex_selective_pelu

config_files:
  - configs/add_test_set.yaml
  - configs/hyper_param_opt/epoch_reduction.yaml
  - configs/vertex_mode.yaml
  - configs/chem/tetra_selective.yaml
  - configs/datasets/rs_dataset.yaml
  - configs/enable_p_elu.yaml
  - configs/models/ptree_default.yaml
  - configs/general.yaml

n_best: 2