loading_dir: results/ez_chienn_unmasked

config_files:
  - configs/unmasked.yaml
  - configs/add_test_set.yaml
  - configs/datasets/ez_dataset.yaml
  - configs/models/chienn.yaml
  - configs/general.yaml

n_best: 2