loading_dir: results/rs_dummy_unmasked

config_files:
  - configs/unmasked.yaml
  - configs/add_test_set.yaml
  - configs/datasets/rs_dataset.yaml
  - configs/models/dummy.yaml
  - configs/general.yaml

n_best: 3